API_KEY = "YOUR_BINANCE_API_KEY"
API_SECRET = "YOUR_BINANCE_SECRET"

SYMBOL = "ETH/USDT"
TIMEFRAME = "1m"

RISK_PER_TRADE = 0.01
LEVERAGE = 5

EMA_FAST = 20
EMA_SLOW = 50

RSI_PERIOD = 14
ATR_PERIOD = 14